### PR TITLE
Cleanup and Figure 3

### PR DESCRIPTION
**Pull request by JustasB**

### CODE REVIEW

**Comment by pgleeson** [comment]
@JustasB, there seems to be a merge conflict with my master branch. Can you merge the latest from my repo into yours and sort out any conflicts?

**Comment by JustasB** [comment]
Merged. The CI build will probably fail. Trying to get omv installed locally... lots of issues, but am getting closer.

**Comment by JustasB** [comment]
Cannot get omv to run locally. Reported issue https://github.com/OpenSourceBrain/osb-model-validation/issues/56. Will check in the changes and let travis do the testing. Aggravating.

**Comment by JustasB** [comment]
@pgleeson Pull request ready. Take a look.

**Comment by pgleeson** [comment]
Looks good!

**Pull request merged**
